Создал компонент, подключил json-данные, реализовал на их основе страницу
htmlacademy-vue/1532589-pizza-1 pull request #1
Opened 2022-09-26 14:48 UTC by Flanderika

2022-09-26 21:54 UTC, enotke requested changes

2022-09-26 21:54 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                  :style="{ '--bgImage': `url('${dough.image}')` }"
Нужно использовать классы `dough__input--light dough__input--large`

2022-09-26 21:54 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                  :style="{ '--bgImage': `url('${size.image}')` }"
Необходимые стили уже есть в классе

2022-09-26 21:54 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                        :style="{ '--bgImage': `url('${ingredient.image}')` }"
нужно использовать классы `filling--mushrooms filling--cheddar...`

2022-09-27 09:37 UTC, Flanderika commented on src/frontend/src/views/Index.vue
> +                  :style="{ '--bgImage': `url('${dough.image}')` }"
Исправил

2022-09-27 09:37 UTC, Flanderika commented on src/frontend/src/views/Index.vue
> +                  :style="{ '--bgImage': `url('${size.image}')` }"
Удалил лишнее

2022-09-27 09:37 UTC, Flanderika commented on src/frontend/src/views/Index.vue
> +                        :style="{ '--bgImage': `url('${ingredient.image}')` }"
Исправил но есть вопрос - 
Разве хорошая практика плодить столько строк кода, если из можно взять из объекта изображение и сделать это одной строкой?

2022-09-27 21:18 UTC, enotke commented on src/frontend/src/views/Index.vue
> +                        :style="{ '--bgImage': `url('${ingredient.image}')` }"
Таковы требования

2022-09-27 21:27 UTC, enotke commented
Ещё нужно этот Index компонент подключить в App и можно приступать к следующему заданию

2022-09-27 21:27 UTC, merged